apiVersion: v1
kind: ConfigMap
metadata:
  name: sriovdp-config
data:
  config.json: |
    {
      "resourceList": [
        {
          "resourcePrefix": "intel.com",
          "resourceName": "intel_sriov_vfio_access",
          "selectors": {
            "vendors": ["8086"],
            "drivers": ["vfio-pci"],
            "pciAddresses": ["0000:60:06.0", "0000:60:06.1", "0000:60:06.2", "0000:60:06.3", "0000:60:06.4", "0000:60:06.5"]
          }
        },
        {
          "resourcePrefix": "intel.com",
          "resourceName": "intel_sriov_vfio_core",
          "selectors": {
            "vendors": ["8086"],
            "drivers": ["vfio-pci"],
            "pciAddresses": ["0000:60:06.6", "0000:60:06.7", "0000:60:07.0", "0000:60:07.1", "0000:60:07.2", "0000:60:07.3"]
          }
        },
        {
          "resourcePrefix": "mellanox.com",
          "resourceName": "mellanox_sriov_netdevice",
          "selectors": {
            "vendors": ["15b3"],
            "devices": ["1016", "1018", "101a", "101c"],
            "drivers": ["mlx5_core"]
          }
        },
        {
          "resourcePrefix": "mellanox.com",
          "resourceName": "mellanox_sriov_vfio",
          "selectors": {
            "vendors": ["15b3"],
            "drivers": ["vfio-pci"]
          }
        }
      ]
    }
